site_name: ChessMaker
site_url: https://wolfdwyc.github.io/ChessMaker/
repo_name: WolfDWyc/ChessMaker
repo_url: https://github.com/WolfDWyc/ChessMaker.git
nav:
  - ChessMaker: index.md
  - Packaged Variants: packaged-variants.md
  - Getting started - Creating a custom game: getting-started.md
  - Creating new variants:
      - First steps: guide/first-steps.md
      - Concepts:
          - Events: guide/concepts/events.md
          - Base Game: guide/concepts/base-game.md
          - Cloneables: guide/concepts/cloneables.md
      - Tutorials:
          - Capture All Pieces to Win - Changing the result function: guide/tutorials/capture-all-pieces-to-win.md
          - Siberian Swipe - Adding move options: guide/tutorials/siberian-swipe.md
          - Forced En Passant - Removing move options: guide/tutorials/forced-en-passant.md
          - Omnipotent F6 Pawn - Adding custom moves: guide/tutorials/omnipotent-f6-pawn.md
          - Knook - Adding a new piece: guide/tutorials/knook.md
  - API Reference:
      - Events: api-reference/events.md
      - Piece Utilities: api-reference/piece-utils.md
      - Game: api-reference/game.md
      - Board: api-reference/board.md
      - Player: api-reference/player.md
      - Position: api-reference/position.md
      - Square: api-reference/square.md
      - Piece: api-reference/piece.md
      - MoveOption: api-reference/move-option.md
      - Rule: api-reference/rule.md
theme:
  name: material
  logo: assets/images/simple-logo-cropped-swapped.png
  favicon: assets/images/simple-logo-cropped.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
