from .beta_decay import BetaDecay
from .forced_en_passant import ForcedEnPassant
from .il_vaticano import IlVaticano
from .knight_boosting import KnightBoosting
from .omnipotent_f6_pawn import OmnipotentF6Pawn
from .siberian_swipe import SiberianSwipe
from .king_cant_move_to_c2 import KingCantMoveToC2
from .la_bastarda import LaBastarda
from .duck_chess import DuckChess
